### ISSUE TITLE
代码中的地图网格是什么意思？有什么作用？

### ISSUE THREAD

**Issue by wrzto** [kennir/ElemeSpider#1]
代码中的地图网格是什么意思？有什么作用？

**Comment by kennir** [comment]
把地图根据经纬度分成多个格子，然后用这个格子的经纬度生成的geohash去eleme查询这个位置里的所有餐厅

**Comment by wrzto** [comment]
嗯嗯，感谢！还有个问题，这个api是在哪里获取的？我看这个api可以直接获取想要的字段，但是现在貌似没有用了

**Comment by kennir** [comment]
嗯，很老了，应该是抓eleme的web端拿到的
